# Welcome to Jekyll!
title: Diego S.C.
email: diegosc@protonmail.com
description: I'm a software, web and musician (why not) developer in new things.
logo: /assets/img/default-logo.png

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://diegosc.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Di_Will
github_username:  diegosozua
linkedin_username: disouzacosta
facebook_username: diegsc

permalink: /:title

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
